"""add requires_expert_review to tool_source and response

Revision ID: 64c84f9901a8
Revises: 7f5ffc57bb41
Create Date: 2026-08-15 23:32:06.678258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c84f9901a8'
down_revision: Union[str, Sequence[str], None] = '7f5ffc57bb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (both tables already have data
    # in every environment this migration will run against) -- autogenerate
    # doesn't add this on its own, only the Python-side default=False.
    op.add_column(
        'response',
        sa.Column('requires_expert_review', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column(
        'tool_source',
        sa.Column('requires_expert_review', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_source', 'requires_expert_review')
    op.drop_column('response', 'requires_expert_review')
    # ### end Alembic commands ###
