"""add grounding_log_channel_id to org

Revision ID: e14bb9ce43aa
Revises: 64c84f9901a8
Create Date: 2026-08-15 23:44:40.078038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14bb9ce43aa'
down_revision: Union[str, Sequence[str], None] = '64c84f9901a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('grounding_log_channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org', 'grounding_log_channel_id')
    # ### end Alembic commands ###
